services:
  jenkins:
    build: .
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
